services:
    - type: web
      name: frontend
      env: docker
      dockerfilePath: ./frontend/Dockerfile
      plan: free

    - type: web
      name: backend
      env: docker
      dockerfilePath: ./backend/Dockerfile
      plan: free
